/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AccessToken
 */
export interface AccessToken {
    /**
     * 
     * @type {number}
     * @memberof AccessToken
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    sha1?: any;
    /**
     * 
     * @type {string}
     * @memberof AccessToken
     */
    token_last_eight?: any;
}
