/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AddCollaboratorOption options when adding a user as a collaborator of a repository
 * @export
 * @interface AddCollaboratorOption
 */
export interface AddCollaboratorOption {
    /**
     * 
     * @type {string}
     * @memberof AddCollaboratorOption
     */
    permission?: any;
}
