/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AnnotatedTag represents an annotated tag
 * @export
 * @interface AnnotatedTag
 */
export interface AnnotatedTag {
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTag
     */
    message?: any;
    /**
     * 
     * @type {AnnotatedTagObject}
     * @memberof AnnotatedTag
     */
    object?: any;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTag
     */
    sha?: any;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTag
     */
    tag?: any;
    /**
     * 
     * @type {CommitUser}
     * @memberof AnnotatedTag
     */
    tagger?: any;
    /**
     * 
     * @type {string}
     * @memberof AnnotatedTag
     */
    url?: any;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof AnnotatedTag
     */
    verification?: any;
}
