/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Attachment a generic attachment
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    browser_download_url?: any;
    /**
     * 
     * @type {Date}
     * @memberof Attachment
     */
    created_at?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    download_count?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof Attachment
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof Attachment
     */
    uuid?: any;
}
