/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * BranchProtection represents a branch protection for a repository
 * @export
 * @interface BranchProtection
 */
export interface BranchProtection {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    approvals_whitelist_teams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    approvals_whitelist_username?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    block_on_official_review_requests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    block_on_outdated_branch?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    block_on_rejected_reviews?: any;
    /**
     * 
     * @type {string}
     * @memberof BranchProtection
     */
    branch_name?: any;
    /**
     * 
     * @type {Date}
     * @memberof BranchProtection
     */
    created_at?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    dismiss_stale_approvals?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enable_approvals_whitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enable_merge_whitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enable_push?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enable_push_whitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enable_status_check?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    merge_whitelist_teams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    merge_whitelist_usernames?: any;
    /**
     * 
     * @type {string}
     * @memberof BranchProtection
     */
    protected_file_patterns?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    push_whitelist_deploy_keys?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    push_whitelist_teams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    push_whitelist_usernames?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    require_signed_commits?: any;
    /**
     * 
     * @type {number}
     * @memberof BranchProtection
     */
    required_approvals?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    status_check_contexts?: any;
    /**
     * 
     * @type {Date}
     * @memberof BranchProtection
     */
    updated_at?: any;
}
