/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * BranchProtection represents a branch protection for a repository
 * @export
 * @interface BranchProtection
 */
export interface BranchProtection {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    approvalsWhitelistTeams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    approvalsWhitelistUsername?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    blockOnOfficialReviewRequests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    blockOnOutdatedBranch?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    blockOnRejectedReviews?: any;
    /**
     * 
     * @type {string}
     * @memberof BranchProtection
     */
    branchName?: any;
    /**
     * 
     * @type {Date}
     * @memberof BranchProtection
     */
    createdAt?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    dismissStaleApprovals?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enableApprovalsWhitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enableMergeWhitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enablePush?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enablePushWhitelist?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    enableStatusCheck?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    mergeWhitelistTeams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    mergeWhitelistUsernames?: any;
    /**
     * 
     * @type {string}
     * @memberof BranchProtection
     */
    protectedFilePatterns?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    pushWhitelistDeployKeys?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    pushWhitelistTeams?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    pushWhitelistUsernames?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BranchProtection
     */
    requireSignedCommits?: any;
    /**
     * 
     * @type {number}
     * @memberof BranchProtection
     */
    requiredApprovals?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof BranchProtection
     */
    statusCheckContexts?: any;
    /**
     * 
     * @type {Date}
     * @memberof BranchProtection
     */
    updatedAt?: any;
}
