/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Branch represents a repository branch
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {PayloadCommit}
     * @memberof Branch
     */
    commit?: any;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    effective_branch_protection_name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    enable_status_check?: any;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    _protected?: any;
    /**
     * 
     * @type {number}
     * @memberof Branch
     */
    required_approvals?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Branch
     */
    status_check_contexts?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    user_can_merge?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    user_can_push?: any;
}
