/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Branch represents a repository branch
 * @export
 * @interface Branch
 */
export interface Branch {
    /**
     * 
     * @type {PayloadCommit}
     * @memberof Branch
     */
    commit?: any;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    effectiveBranchProtectionName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    enableStatusCheck?: any;
    /**
     * 
     * @type {string}
     * @memberof Branch
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    _protected?: any;
    /**
     * 
     * @type {number}
     * @memberof Branch
     */
    requiredApprovals?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Branch
     */
    statusCheckContexts?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    userCanMerge?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Branch
     */
    userCanPush?: any;
}
