/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CombinedStatus holds the combined state of several statuses for a single commit
 * @export
 * @interface CombinedStatus
 */
export interface CombinedStatus {
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    commit_url?: any;
    /**
     * 
     * @type {Repository}
     * @memberof CombinedStatus
     */
    repository?: any;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    sha?: any;
    /**
     * 
     * @type {CommitStatusState}
     * @memberof CombinedStatus
     */
    state?: any;
    /**
     * 
     * @type {Array&lt;CommitStatus&gt;}
     * @memberof CombinedStatus
     */
    statuses?: any;
    /**
     * 
     * @type {number}
     * @memberof CombinedStatus
     */
    total_count?: any;
    /**
     * 
     * @type {string}
     * @memberof CombinedStatus
     */
    url?: any;
}
