/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CommitDateOptions store dates for GIT_AUTHOR_DATE and GIT_COMMITTER_DATE
 * @export
 * @interface CommitDateOptions
 */
export interface CommitDateOptions {
    /**
     * 
     * @type {Date}
     * @memberof CommitDateOptions
     */
    author?: any;
    /**
     * 
     * @type {Date}
     * @memberof CommitDateOptions
     */
    committer?: any;
}
