/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Commit
 */
export interface Commit {
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    author?: any;
    /**
     * 
     * @type {RepoCommit}
     * @memberof Commit
     */
    commit?: any;
    /**
     * 
     * @type {User}
     * @memberof Commit
     */
    committer?: any;
    /**
     * 
     * @type {Date}
     * @memberof Commit
     */
    created?: any;
    /**
     * 
     * @type {Array&lt;CommitAffectedFiles&gt;}
     * @memberof Commit
     */
    files?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    htmlUrl?: any;
    /**
     * 
     * @type {Array&lt;CommitMeta&gt;}
     * @memberof Commit
     */
    parents?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    sha?: any;
    /**
     * 
     * @type {string}
     * @memberof Commit
     */
    url?: any;
}
