/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Comment represents a comment on a commit or issue
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    issueUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    originalAuthor?: any;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    originalAuthorId?: any;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    pullRequestUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof Comment
     */
    updatedAt?: any;
    /**
     * 
     * @type {User}
     * @memberof Comment
     */
    user?: any;
}
