/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * ContentsResponse contains information about a repo's entry's (dir, file, symlink, submodule) metadata and content
 * @export
 * @interface ContentsResponse
 */
export interface ContentsResponse {
    /**
     * 
     * @type {FileLinksResponse}
     * @memberof ContentsResponse
     */
    links?: any;
    /**
     * `content` is populated when `type` is `file`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    content?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    downloadUrl?: any;
    /**
     * `encoding` is populated when `type` is `file`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    encoding?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    gitUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    htmlUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    path?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    sha?: any;
    /**
     * 
     * @type {number}
     * @memberof ContentsResponse
     */
    size?: any;
    /**
     * `submodule_git_url` is populated when `type` is `submodule`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    submoduleGitUrl?: any;
    /**
     * `target` is populated when `type` is `symlink`, otherwise null
     * @type {string}
     * @memberof ContentsResponse
     */
    target?: any;
    /**
     * `type` will be `file`, `dir`, `symlink`, or `submodule`
     * @type {string}
     * @memberof ContentsResponse
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof ContentsResponse
     */
    url?: any;
}
