/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateFileOptions options for creating files Note: `author` and `committer` are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
 * @export
 * @interface CreateFileOptions
 */
export interface CreateFileOptions {
    /**
     * 
     * @type {Identity}
     * @memberof CreateFileOptions
     */
    author?: any;
    /**
     * branch (optional) to base this file from. if not given, the default branch is used
     * @type {string}
     * @memberof CreateFileOptions
     */
    branch?: any;
    /**
     * 
     * @type {Identity}
     * @memberof CreateFileOptions
     */
    committer?: any;
    /**
     * content must be base64 encoded
     * @type {string}
     * @memberof CreateFileOptions
     */
    content: any;
    /**
     * 
     * @type {CommitDateOptions}
     * @memberof CreateFileOptions
     */
    dates?: any;
    /**
     * message (optional) for the commit of this file. if not supplied, a default message will be used
     * @type {string}
     * @memberof CreateFileOptions
     */
    message?: any;
    /**
     * new_branch (optional) will make a new branch from `branch` before creating the file
     * @type {string}
     * @memberof CreateFileOptions
     */
    new_branch?: any;
    /**
     * Add a Signed-off-by trailer by the committer at the end of the commit log message.
     * @type {boolean}
     * @memberof CreateFileOptions
     */
    signoff?: any;
}
