/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateKeyOption options when creating a key
 * @export
 * @interface CreateKeyOption
 */
export interface CreateKeyOption {
    /**
     * An armored SSH key to add
     * @type {string}
     * @memberof CreateKeyOption
     */
    key: any;
    /**
     * Describe if the key has only read access or read/write
     * @type {boolean}
     * @memberof CreateKeyOption
     */
    read_only?: any;
    /**
     * Title of the key to add
     * @type {string}
     * @memberof CreateKeyOption
     */
    title: any;
}
