/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateRepoOption options when creating repository
 * @export
 * @interface CreateRepoOption
 */
export interface CreateRepoOption {
    /**
     * Whether the repository should be auto-intialized?
     * @type {boolean}
     * @memberof CreateRepoOption
     */
    auto_init?: any;
    /**
     * DefaultBranch of the repository (used when initializes and in template)
     * @type {string}
     * @memberof CreateRepoOption
     */
    default_branch?: any;
    /**
     * Description of the repository to create
     * @type {string}
     * @memberof CreateRepoOption
     */
    description?: any;
    /**
     * Gitignores to use
     * @type {string}
     * @memberof CreateRepoOption
     */
    gitignores?: any;
    /**
     * Label-Set to use
     * @type {string}
     * @memberof CreateRepoOption
     */
    issue_labels?: any;
    /**
     * License to use
     * @type {string}
     * @memberof CreateRepoOption
     */
    license?: any;
    /**
     * Name of the repository to create
     * @type {string}
     * @memberof CreateRepoOption
     */
    name: any;
    /**
     * Whether the repository is private
     * @type {boolean}
     * @memberof CreateRepoOption
     */
    _private?: any;
    /**
     * Readme of the repository to create
     * @type {string}
     * @memberof CreateRepoOption
     */
    readme?: any;
    /**
     * Whether the repository is template
     * @type {boolean}
     * @memberof CreateRepoOption
     */
    template?: any;
    /**
     * TrustModel of the repository
     * @type {string}
     * @memberof CreateRepoOption
     */
    trust_model?: CreateRepoOptionTrustModelEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateRepoOptionTrustModelEnum {
    Default = 'default',
    Collaborator = 'collaborator',
    Committer = 'committer',
    Collaboratorcommitter = 'collaboratorcommitter'
}

