/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateMilestoneOption options for creating a milestone
 * @export
 * @interface CreateMilestoneOption
 */
export interface CreateMilestoneOption {
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    description?: any;
    /**
     * 
     * @type {Date}
     * @memberof CreateMilestoneOption
     */
    due_on?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    state?: CreateMilestoneOptionStateEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateMilestoneOption
     */
    title?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum CreateMilestoneOptionStateEnum {
    Open = 'open',
    Closed = 'closed'
}

