/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreatePullReviewComment represent a review comment for creation api
 * @export
 * @interface CreatePullReviewComment
 */
export interface CreatePullReviewComment {
    /**
     * 
     * @type {string}
     * @memberof CreatePullReviewComment
     */
    body?: any;
    /**
     * if comment to new file line or 0
     * @type {number}
     * @memberof CreatePullReviewComment
     */
    new_position?: any;
    /**
     * if comment to old file line or 0
     * @type {number}
     * @memberof CreatePullReviewComment
     */
    old_position?: any;
    /**
     * the tree path
     * @type {string}
     * @memberof CreatePullReviewComment
     */
    path?: any;
}
