/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateUserOption create user options
 * @export
 * @interface CreateUserOption
 */
export interface CreateUserOption {
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    fullName?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    loginName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserOption
     */
    mustChangePassword?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    password: any;
    /**
     * 
     * @type {boolean}
     * @memberof CreateUserOption
     */
    sendNotify?: any;
    /**
     * 
     * @type {number}
     * @memberof CreateUserOption
     */
    sourceId?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateUserOption
     */
    username: any;
}
