/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateIssueCommentOption options for creating a comment on an issue
 * @export
 * @interface CreateIssueCommentOption
 */
export interface CreateIssueCommentOption {
    /**
     * 
     * @type {string}
     * @memberof CreateIssueCommentOption
     */
    body: any;
}
