/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * CreateIssueOption options to create one issue
 * @export
 * @interface CreateIssueOption
 */
export interface CreateIssueOption {
    /**
     * deprecated
     * @type {string}
     * @memberof CreateIssueOption
     */
    assignee?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof CreateIssueOption
     */
    assignees?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueOption
     */
    body?: any;
    /**
     * 
     * @type {boolean}
     * @memberof CreateIssueOption
     */
    closed?: any;
    /**
     * 
     * @type {Date}
     * @memberof CreateIssueOption
     */
    dueDate?: any;
    /**
     * list of label ids
     * @type {Array&lt;number&gt;}
     * @memberof CreateIssueOption
     */
    labels?: any;
    /**
     * milestone id
     * @type {number}
     * @memberof CreateIssueOption
     */
    milestone?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueOption
     */
    ref?: any;
    /**
     * 
     * @type {string}
     * @memberof CreateIssueOption
     */
    title: any;
}
