/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * DeleteFileOptions options for deleting files (used for other File structs below) Note: `author` and `committer` are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
 * @export
 * @interface DeleteFileOptions
 */
export interface DeleteFileOptions {
    /**
     * 
     * @type {Identity}
     * @memberof DeleteFileOptions
     */
    author?: any;
    /**
     * branch (optional) to base this file from. if not given, the default branch is used
     * @type {string}
     * @memberof DeleteFileOptions
     */
    branch?: any;
    /**
     * 
     * @type {Identity}
     * @memberof DeleteFileOptions
     */
    committer?: any;
    /**
     * 
     * @type {CommitDateOptions}
     * @memberof DeleteFileOptions
     */
    dates?: any;
    /**
     * message (optional) for the commit of this file. if not supplied, a default message will be used
     * @type {string}
     * @memberof DeleteFileOptions
     */
    message?: any;
    /**
     * new_branch (optional) will make a new branch from `branch` before creating the file
     * @type {string}
     * @memberof DeleteFileOptions
     */
    newBranch?: any;
    /**
     * sha is the SHA for the file that already exists
     * @type {string}
     * @memberof DeleteFileOptions
     */
    sha: any;
    /**
     * Add a Signed-off-by trailer by the committer at the end of the commit log message.
     * @type {boolean}
     * @memberof DeleteFileOptions
     */
    signoff?: any;
}
