/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * DeployKey a deploy key
 * @export
 * @interface DeployKey
 */
export interface DeployKey {
    /**
     * 
     * @type {Date}
     * @memberof DeployKey
     */
    created_at?: any;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    fingerprint?: any;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    key?: any;
    /**
     * 
     * @type {number}
     * @memberof DeployKey
     */
    key_id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof DeployKey
     */
    read_only?: any;
    /**
     * 
     * @type {Repository}
     * @memberof DeployKey
     */
    repository?: any;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof DeployKey
     */
    url?: any;
}
