/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditTeamOption options for editing a team
 * @export
 * @interface EditTeamOption
 */
export interface EditTeamOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditTeamOption
     */
    canCreateOrgRepo?: any;
    /**
     * 
     * @type {string}
     * @memberof EditTeamOption
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditTeamOption
     */
    includesAllRepositories?: any;
    /**
     * 
     * @type {string}
     * @memberof EditTeamOption
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof EditTeamOption
     */
    permission?: EditTeamOptionPermissionEnum;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof EditTeamOption
     */
    units?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum EditTeamOptionPermissionEnum {
    Read = 'read',
    Write = 'write',
    Admin = 'admin'
}

