/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditReleaseOption options when editing a release
 * @export
 * @interface EditReleaseOption
 */
export interface EditReleaseOption {
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    body?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditReleaseOption
     */
    draft?: any;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditReleaseOption
     */
    prerelease?: any;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    tagName?: any;
    /**
     * 
     * @type {string}
     * @memberof EditReleaseOption
     */
    targetCommitish?: any;
}
