/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditUserOption edit user options
 * @export
 * @interface EditUserOption
 */
export interface EditUserOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    active?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    admin?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowCreateOrganization?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowGitHook?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allowImportLocal?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    fullName?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    location?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    loginName: any;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    maxRepoCreation?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    mustChangePassword?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    prohibitLogin?: any;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    sourceId: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    website?: any;
}
