/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditUserOption edit user options
 * @export
 * @interface EditUserOption
 */
export interface EditUserOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    active?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    admin?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allow_create_organization?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allow_git_hook?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    allow_import_local?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    email?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    full_name?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    location?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    login_name: any;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    max_repo_creation?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    must_change_password?: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    password?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    prohibit_login?: any;
    /**
     * 
     * @type {boolean}
     * @memberof EditUserOption
     */
    restricted?: any;
    /**
     * 
     * @type {number}
     * @memberof EditUserOption
     */
    source_id: any;
    /**
     * 
     * @type {string}
     * @memberof EditUserOption
     */
    website?: any;
}
