/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditHookOption options when modify one hook
 * @export
 * @interface EditHookOption
 */
export interface EditHookOption {
    /**
     * 
     * @type {boolean}
     * @memberof EditHookOption
     */
    active?: any;
    /**
     * 
     * @type {string}
     * @memberof EditHookOption
     */
    branch_filter?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof EditHookOption
     */
    config?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof EditHookOption
     */
    events?: any;
}
