/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditMilestoneOption options for editing a milestone
 * @export
 * @interface EditMilestoneOption
 */
export interface EditMilestoneOption {
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    description?: any;
    /**
     * 
     * @type {Date}
     * @memberof EditMilestoneOption
     */
    due_on?: any;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof EditMilestoneOption
     */
    title?: any;
}
