/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditGitHookOption options when modifying one Git hook
 * @export
 * @interface EditGitHookOption
 */
export interface EditGitHookOption {
    /**
     * 
     * @type {string}
     * @memberof EditGitHookOption
     */
    content?: any;
}
