/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * EditRepoOption options when editing a repository's properties
 * @export
 * @interface EditRepoOption
 */
export interface EditRepoOption {
    /**
     * either `true` to allow merging pull requests with a merge commit, or `false` to prevent merging pull requests with merge commits. `has_pull_requests` must be `true`.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    allowMergeCommits?: any;
    /**
     * either `true` to allow rebase-merging pull requests, or `false` to prevent rebase-merging. `has_pull_requests` must be `true`.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    allowRebase?: any;
    /**
     * either `true` to allow rebase with explicit merge commits (--no-ff), or `false` to prevent rebase with explicit merge commits. `has_pull_requests` must be `true`.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    allowRebaseExplicit?: any;
    /**
     * either `true` to allow squash-merging pull requests, or `false` to prevent squash-merging. `has_pull_requests` must be `true`.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    allowSquashMerge?: any;
    /**
     * set to `true` to archive this repository.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    archived?: any;
    /**
     * sets the default branch for this repository.
     * @type {string}
     * @memberof EditRepoOption
     */
    defaultBranch?: any;
    /**
     * a short description of the repository.
     * @type {string}
     * @memberof EditRepoOption
     */
    description?: any;
    /**
     * 
     * @type {ExternalTracker}
     * @memberof EditRepoOption
     */
    externalTracker?: any;
    /**
     * 
     * @type {ExternalWiki}
     * @memberof EditRepoOption
     */
    externalWiki?: any;
    /**
     * either `true` to enable issues for this repository or `false` to disable them.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    hasIssues?: any;
    /**
     * either `true` to enable project unit, or `false` to disable them.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    hasProjects?: any;
    /**
     * either `true` to allow pull requests, or `false` to prevent pull request.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    hasPullRequests?: any;
    /**
     * either `true` to enable the wiki for this repository or `false` to disable it.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    hasWiki?: any;
    /**
     * either `true` to ignore whitespace for conflicts, or `false` to not ignore whitespace. `has_pull_requests` must be `true`.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    ignoreWhitespaceConflicts?: any;
    /**
     * 
     * @type {InternalTracker}
     * @memberof EditRepoOption
     */
    internalTracker?: any;
    /**
     * set to a string like `8h30m0s` to set the mirror interval time
     * @type {string}
     * @memberof EditRepoOption
     */
    mirrorInterval?: any;
    /**
     * name of the repository
     * @type {string}
     * @memberof EditRepoOption
     */
    name?: any;
    /**
     * either `true` to make the repository private or `false` to make it public. Note: you will get a 422 error if the organization restricts changing repository visibility to organization owners and a non-owner tries to change the value of private.
     * @type {boolean}
     * @memberof EditRepoOption
     */
    _private?: any;
    /**
     * either `true` to make this repository a template or `false` to make it a normal repository
     * @type {boolean}
     * @memberof EditRepoOption
     */
    template?: any;
    /**
     * a URL with more information about the repository.
     * @type {string}
     * @memberof EditRepoOption
     */
    website?: any;
}
