/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * ExternalWiki represents setting for external wiki
 * @export
 * @interface ExternalWiki
 */
export interface ExternalWiki {
    /**
     * URL of external wiki.
     * @type {string}
     * @memberof ExternalWiki
     */
    external_wiki_url?: any;
}
