/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * FileResponse contains information about a repo's file
 * @export
 * @interface FileResponse
 */
export interface FileResponse {
    /**
     * 
     * @type {FileCommitResponse}
     * @memberof FileResponse
     */
    commit?: any;
    /**
     * 
     * @type {ContentsResponse}
     * @memberof FileResponse
     */
    content?: any;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof FileResponse
     */
    verification?: any;
}
