/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAttachmentSettings contains global Attachment settings exposed by API
 * @export
 * @interface GeneralAttachmentSettings
 */
export interface GeneralAttachmentSettings {
    /**
     * 
     * @type {string}
     * @memberof GeneralAttachmentSettings
     */
    allowed_types?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralAttachmentSettings
     */
    enabled?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    max_files?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    max_size?: any;
}
