/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAPISettings contains global api settings exposed by it
 * @export
 * @interface GeneralAPISettings
 */
export interface GeneralAPISettings {
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    default_git_trees_per_page?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    default_max_blob_size?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    default_paging_num?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    max_response_items?: any;
}
