/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAPISettings contains global api settings exposed by it
 * @export
 * @interface GeneralAPISettings
 */
export interface GeneralAPISettings {
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultGitTreesPerPage?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultMaxBlobSize?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    defaultPagingNum?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAPISettings
     */
    maxResponseItems?: any;
}
