/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralAttachmentSettings contains global Attachment settings exposed by API
 * @export
 * @interface GeneralAttachmentSettings
 */
export interface GeneralAttachmentSettings {
    /**
     * 
     * @type {string}
     * @memberof GeneralAttachmentSettings
     */
    allowedTypes?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralAttachmentSettings
     */
    enabled?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    maxFiles?: any;
    /**
     * 
     * @type {number}
     * @memberof GeneralAttachmentSettings
     */
    maxSize?: any;
}
