/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralUISettings contains global ui settings exposed by API
 * @export
 * @interface GeneralUISettings
 */
export interface GeneralUISettings {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof GeneralUISettings
     */
    allowed_reactions?: any;
    /**
     * 
     * @type {string}
     * @memberof GeneralUISettings
     */
    default_theme?: any;
}
