/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GeneralRepoSettings contains global repository settings exposed by API
 * @export
 * @interface GeneralRepoSettings
 */
export interface GeneralRepoSettings {
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    httpGitDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    migrationsDisabled?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GeneralRepoSettings
     */
    mirrorsDisabled?: any;
}
