/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GitEntry represents a git tree
 * @export
 * @interface GitEntry
 */
export interface GitEntry {
    /**
     * 
     * @type {string}
     * @memberof GitEntry
     */
    mode?: any;
    /**
     * 
     * @type {string}
     * @memberof GitEntry
     */
    path?: any;
    /**
     * 
     * @type {string}
     * @memberof GitEntry
     */
    sha?: any;
    /**
     * 
     * @type {number}
     * @memberof GitEntry
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof GitEntry
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof GitEntry
     */
    url?: any;
}
