/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GitTreeResponse returns a git tree
 * @export
 * @interface GitTreeResponse
 */
export interface GitTreeResponse {
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    page?: any;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    sha?: any;
    /**
     * 
     * @type {number}
     * @memberof GitTreeResponse
     */
    total_count?: any;
    /**
     * 
     * @type {Array&lt;GitEntry&gt;}
     * @memberof GitTreeResponse
     */
    tree?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GitTreeResponse
     */
    truncated?: any;
    /**
     * 
     * @type {string}
     * @memberof GitTreeResponse
     */
    url?: any;
}
