/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GPGKey a user GPG key to sign commit and tag in repository
 * @export
 * @interface GPGKey
 */
export interface GPGKey {
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    can_certify?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    can_encrypt_comms?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    can_encrypt_storage?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    can_sign?: any;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    created_at?: any;
    /**
     * 
     * @type {Array&lt;GPGKeyEmail&gt;}
     * @memberof GPGKey
     */
    emails?: any;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    expires_at?: any;
    /**
     * 
     * @type {number}
     * @memberof GPGKey
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    key_id?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    primary_key_id?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    public_key?: any;
    /**
     * 
     * @type {Array&lt;GPGKey&gt;}
     * @memberof GPGKey
     */
    subkeys?: any;
}
