/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * GPGKey a user GPG key to sign commit and tag in repository
 * @export
 * @interface GPGKey
 */
export interface GPGKey {
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canCertify?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canEncryptComms?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canEncryptStorage?: any;
    /**
     * 
     * @type {boolean}
     * @memberof GPGKey
     */
    canSign?: any;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    createdAt?: any;
    /**
     * 
     * @type {Array&lt;GPGKeyEmail&gt;}
     * @memberof GPGKey
     */
    emails?: any;
    /**
     * 
     * @type {Date}
     * @memberof GPGKey
     */
    expiresAt?: any;
    /**
     * 
     * @type {number}
     * @memberof GPGKey
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    keyId?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    primaryKeyId?: any;
    /**
     * 
     * @type {string}
     * @memberof GPGKey
     */
    publicKey?: any;
    /**
     * 
     * @type {Array&lt;GPGKey&gt;}
     * @memberof GPGKey
     */
    subkeys?: any;
}
