/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Hook a hook is a web hook when one repository changed
 * @export
 * @interface Hook
 */
export interface Hook {
    /**
     * 
     * @type {boolean}
     * @memberof Hook
     */
    active?: any;
    /**
     * 
     * @type {{ [key, string]: string;}}
     * @memberof Hook
     */
    config?: any;
    /**
     * 
     * @type {Date}
     * @memberof Hook
     */
    created_at?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Hook
     */
    events?: any;
    /**
     * 
     * @type {number}
     * @memberof Hook
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Hook
     */
    type?: any;
    /**
     * 
     * @type {Date}
     * @memberof Hook
     */
    updated_at?: any;
}
