/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Issue represents an issue in a repository
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    assignee?: any;
    /**
     * 
     * @type {Array&lt;User&gt;}
     * @memberof Issue
     */
    assignees?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    closed_at?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    comments?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    created_at?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    due_date?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    html_url?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    is_locked?: any;
    /**
     * 
     * @type {Array&lt;Label&gt;}
     * @memberof Issue
     */
    labels?: any;
    /**
     * 
     * @type {Milestone}
     * @memberof Issue
     */
    milestone?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    number?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    original_author?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    original_author_id?: any;
    /**
     * 
     * @type {PullRequestMeta}
     * @memberof Issue
     */
    pull_request?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    ref?: any;
    /**
     * 
     * @type {RepositoryMeta}
     * @memberof Issue
     */
    repository?: any;
    /**
     * 
     * @type {StateType}
     * @memberof Issue
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    updated_at?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    user?: any;
}
