/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Issue represents an issue in a repository
 * @export
 * @interface Issue
 */
export interface Issue {
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    assignee?: any;
    /**
     * 
     * @type {Array&lt;User&gt;}
     * @memberof Issue
     */
    assignees?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    closedAt?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    comments?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    createdAt?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    dueDate?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Issue
     */
    isLocked?: any;
    /**
     * 
     * @type {Array&lt;Label&gt;}
     * @memberof Issue
     */
    labels?: any;
    /**
     * 
     * @type {Milestone}
     * @memberof Issue
     */
    milestone?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    number?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    originalAuthor?: any;
    /**
     * 
     * @type {number}
     * @memberof Issue
     */
    originalAuthorId?: any;
    /**
     * 
     * @type {PullRequestMeta}
     * @memberof Issue
     */
    pullRequest?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    ref?: any;
    /**
     * 
     * @type {RepositoryMeta}
     * @memberof Issue
     */
    repository?: any;
    /**
     * 
     * @type {StateType}
     * @memberof Issue
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof Issue
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof Issue
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof Issue
     */
    user?: any;
}
