/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * IssueTemplate represents an issue template for a repository
 * @export
 * @interface IssueTemplate
 */
export interface IssueTemplate {
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    about?: any;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    content?: any;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    file_name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof IssueTemplate
     */
    labels?: any;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof IssueTemplate
     */
    title?: any;
}
