/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Label a label to an issue or a pr
 * @export
 * @interface Label
 */
export interface Label {
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    color?: any;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof Label
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof Label
     */
    url?: any;
}
