/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MarkdownOption markdown options
 * @export
 * @interface MarkdownOption
 */
export interface MarkdownOption {
    /**
     * Context to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    Context?: any;
    /**
     * Mode to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    Mode?: any;
    /**
     * Text markdown to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    Text?: any;
    /**
     * Is it a wiki page ?  in: body
     * @type {boolean}
     * @memberof MarkdownOption
     */
    Wiki?: any;
}
