/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MarkdownOption markdown options
 * @export
 * @interface MarkdownOption
 */
export interface MarkdownOption {
    /**
     * Context to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    context?: any;
    /**
     * Mode to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    mode?: any;
    /**
     * Text markdown to render  in: body
     * @type {string}
     * @memberof MarkdownOption
     */
    text?: any;
    /**
     * Is it a wiki page ?  in: body
     * @type {boolean}
     * @memberof MarkdownOption
     */
    wiki?: any;
}
