/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MergePullRequestForm form for merging Pull Request
 * @export
 * @interface MergePullRequestOption
 */
export interface MergePullRequestOption {
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    _Do: MergePullRequestOptionDoEnum;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    MergeCommitID?: any;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    MergeMessageField?: any;
    /**
     * 
     * @type {string}
     * @memberof MergePullRequestOption
     */
    MergeTitleField?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MergePullRequestOption
     */
    force_merge?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum MergePullRequestOptionDoEnum {
    Merge = 'merge',
    Rebase = 'rebase',
    RebaseMerge = 'rebase-merge',
    Squash = 'squash',
    ManuallyMerged = 'manually-merged'
}

