/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MigrateRepoOptions options for migrating repository's this is used to interact with api v1
 * @export
 * @interface MigrateRepoOptions
 */
export interface MigrateRepoOptions {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authPassword?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authToken?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    authUsername?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    cloneAddr: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    issues?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    labels?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    milestones?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    mirror?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    mirrorInterval?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    _private?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    pullRequests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    releases?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    repoName: any;
    /**
     * Name of User or Organisation who will own Repo after migration
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    repoOwner?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoOptions
     */
    service?: MigrateRepoOptionsServiceEnum;
    /**
     * deprecated (only for backwards compatibility)
     * @type {number}
     * @memberof MigrateRepoOptions
     */
    uid?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoOptions
     */
    wiki?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum MigrateRepoOptionsServiceEnum {
    Git = 'git',
    Github = 'github',
    Gitea = 'gitea',
    Gitlab = 'gitlab'
}

