/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MigrateRepoForm form for migrating repository this is used to interact with web ui
 * @export
 * @interface MigrateRepoForm
 */
export interface MigrateRepoForm {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    auth_password?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    auth_token?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    auth_username?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    clone_addr: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    issues?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    labels?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    milestones?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    mirror?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    mirror_interval?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    _private?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    pull_requests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    releases?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    repo_name: any;
    /**
     * 
     * @type {GitServiceType}
     * @memberof MigrateRepoForm
     */
    service?: any;
    /**
     * 
     * @type {number}
     * @memberof MigrateRepoForm
     */
    uid: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    wiki?: any;
}
