/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * MigrateRepoForm form for migrating repository this is used to interact with web ui
 * @export
 * @interface MigrateRepoForm
 */
export interface MigrateRepoForm {
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authPassword?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authToken?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    authUsername?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    cloneAddr: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    issues?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    labels?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    milestones?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    mirror?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    mirrorInterval?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    _private?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    pullRequests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    releases?: any;
    /**
     * 
     * @type {string}
     * @memberof MigrateRepoForm
     */
    repoName: any;
    /**
     * 
     * @type {GitServiceType}
     * @memberof MigrateRepoForm
     */
    service?: any;
    /**
     * 
     * @type {number}
     * @memberof MigrateRepoForm
     */
    uid: any;
    /**
     * 
     * @type {boolean}
     * @memberof MigrateRepoForm
     */
    wiki?: any;
}
