/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Milestone milestone is a collection of issues on one repository
 * @export
 * @interface Milestone
 */
export interface Milestone {
    /**
     * 
     * @type {Date}
     * @memberof Milestone
     */
    closed_at?: any;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    closed_issues?: any;
    /**
     * 
     * @type {Date}
     * @memberof Milestone
     */
    created_at?: any;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    description?: any;
    /**
     * 
     * @type {Date}
     * @memberof Milestone
     */
    due_on?: any;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    open_issues?: any;
    /**
     * 
     * @type {StateType}
     * @memberof Milestone
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof Milestone
     */
    updated_at?: any;
}
