/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * NotificationThread expose Notification on API
 * @export
 * @interface NotificationThread
 */
export interface NotificationThread {
    /**
     * 
     * @type {number}
     * @memberof NotificationThread
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationThread
     */
    pinned?: any;
    /**
     * 
     * @type {Repository}
     * @memberof NotificationThread
     */
    repository?: any;
    /**
     * 
     * @type {NotificationSubject}
     * @memberof NotificationThread
     */
    subject?: any;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationThread
     */
    unread?: any;
    /**
     * 
     * @type {Date}
     * @memberof NotificationThread
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof NotificationThread
     */
    url?: any;
}
