/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * NotificationSubject contains the notification subject (Issue/Pull/Commit)
 * @export
 * @interface NotificationSubject
 */
export interface NotificationSubject {
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    latestCommentUrl?: any;
    /**
     * 
     * @type {StateType}
     * @memberof NotificationSubject
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    type?: any;
    /**
     * 
     * @type {string}
     * @memberof NotificationSubject
     */
    url?: any;
}
