/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OAuth2Application
 */
export interface OAuth2Application {
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    client_id?: any;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    client_secret?: any;
    /**
     * 
     * @type {Date}
     * @memberof OAuth2Application
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof OAuth2Application
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof OAuth2Application
     */
    name?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof OAuth2Application
     */
    redirect_uris?: any;
}
