/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Organization represents an organization
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    avatarUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    description?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    fullName?: any;
    /**
     * 
     * @type {number}
     * @memberof Organization
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    location?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    repoAdminChangeTeamAccess?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    visibility?: any;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    website?: any;
}
