/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PayloadCommit represents a commit
 * @export
 * @interface PayloadCommit
 */
export interface PayloadCommit {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof PayloadCommit
     */
    added?: any;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    author?: any;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommit
     */
    committer?: any;
    /**
     * sha1 hash of the commit
     * @type {string}
     * @memberof PayloadCommit
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    message?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof PayloadCommit
     */
    modified?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof PayloadCommit
     */
    removed?: any;
    /**
     * 
     * @type {Date}
     * @memberof PayloadCommit
     */
    timestamp?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommit
     */
    url?: any;
    /**
     * 
     * @type {PayloadCommitVerification}
     * @memberof PayloadCommit
     */
    verification?: any;
}
