/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PayloadCommitVerification represents the GPG verification of a commit
 * @export
 * @interface PayloadCommitVerification
 */
export interface PayloadCommitVerification {
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    payload?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    reason?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadCommitVerification
     */
    signature?: any;
    /**
     * 
     * @type {PayloadUser}
     * @memberof PayloadCommitVerification
     */
    signer?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PayloadCommitVerification
     */
    verified?: any;
}
