/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PayloadUser represents the author or committer of a commit
 * @export
 * @interface PayloadUser
 */
export interface PayloadUser {
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    email?: any;
    /**
     * Full name of the commit author
     * @type {string}
     * @memberof PayloadUser
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof PayloadUser
     */
    username?: any;
}
