/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PRBranchInfo information about a branch
 * @export
 * @interface PRBranchInfo
 */
export interface PRBranchInfo {
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    label?: any;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    ref?: any;
    /**
     * 
     * @type {Repository}
     * @memberof PRBranchInfo
     */
    repo?: any;
    /**
     * 
     * @type {number}
     * @memberof PRBranchInfo
     */
    repo_id?: any;
    /**
     * 
     * @type {string}
     * @memberof PRBranchInfo
     */
    sha?: any;
}
