/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PublicKey publickey is a user key to push code to repository
 * @export
 * @interface PublicKey
 */
export interface PublicKey {
    /**
     * 
     * @type {Date}
     * @memberof PublicKey
     */
    created_at?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    fingerprint?: any;
    /**
     * 
     * @type {number}
     * @memberof PublicKey
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    key?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    key_type?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PublicKey
     */
    read_only?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    title?: any;
    /**
     * 
     * @type {string}
     * @memberof PublicKey
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof PublicKey
     */
    user?: any;
}
