/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullReview represents a pull request review
 * @export
 * @interface PullReview
 */
export interface PullReview {
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    body?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    commentsCount?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    commitId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    dismissed?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    official?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    pullRequestUrl?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    stale?: any;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof PullReview
     */
    state?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullReview
     */
    submittedAt?: any;
    /**
     * 
     * @type {Team}
     * @memberof PullReview
     */
    team?: any;
    /**
     * 
     * @type {User}
     * @memberof PullReview
     */
    user?: any;
}
