/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullReviewComment represents a comment on a pull request review
 * @export
 * @interface PullReviewComment
 */
export interface PullReviewComment {
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    body?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    commitId?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullReviewComment
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    diffHunk?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    originalCommitId?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    originalPosition?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    path?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    position?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReviewComment
     */
    pullRequestReviewId?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReviewComment
     */
    pullRequestUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullReviewComment
     */
    updatedAt?: any;
    /**
     * 
     * @type {User}
     * @memberof PullReviewComment
     */
    user?: any;
}
