/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullRequest represents a pull request
 * @export
 * @interface PullRequest
 */
export interface PullRequest {
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    assignee?: any;
    /**
     * 
     * @type {Array&lt;User&gt;}
     * @memberof PullRequest
     */
    assignees?: any;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    base?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    closedAt?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    comments?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    diffUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    dueDate?: any;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    head?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    isLocked?: any;
    /**
     * 
     * @type {Array&lt;Label&gt;}
     * @memberof PullRequest
     */
    labels?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    mergeBase?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    mergeCommitSha?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    mergeable?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    merged?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    mergedAt?: any;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    mergedBy?: any;
    /**
     * 
     * @type {Milestone}
     * @memberof PullRequest
     */
    milestone?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    number?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    patchUrl?: any;
    /**
     * 
     * @type {StateType}
     * @memberof PullRequest
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    user?: any;
}
