/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullReview represents a pull request review
 * @export
 * @interface PullReview
 */
export interface PullReview {
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    body?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    comments_count?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    commit_id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    dismissed?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    html_url?: any;
    /**
     * 
     * @type {number}
     * @memberof PullReview
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    official?: any;
    /**
     * 
     * @type {string}
     * @memberof PullReview
     */
    pull_request_url?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullReview
     */
    stale?: any;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof PullReview
     */
    state?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullReview
     */
    submitted_at?: any;
    /**
     * 
     * @type {Team}
     * @memberof PullReview
     */
    team?: any;
    /**
     * 
     * @type {User}
     * @memberof PullReview
     */
    user?: any;
}
