/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullReviewRequestOptions are options to add or remove pull review requests
 * @export
 * @interface PullReviewRequestOptions
 */
export interface PullReviewRequestOptions {
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof PullReviewRequestOptions
     */
    reviewers?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof PullReviewRequestOptions
     */
    teamReviewers?: any;
}
