/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * PullRequest represents a pull request
 * @export
 * @interface PullRequest
 */
export interface PullRequest {
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    assignee?: any;
    /**
     * 
     * @type {Array&lt;User&gt;}
     * @memberof PullRequest
     */
    assignees?: any;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    base?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    closed_at?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    comments?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    created_at?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    diff_url?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    due_date?: any;
    /**
     * 
     * @type {PRBranchInfo}
     * @memberof PullRequest
     */
    head?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    html_url?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    is_locked?: any;
    /**
     * 
     * @type {Array&lt;Label&gt;}
     * @memberof PullRequest
     */
    labels?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    merge_base?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    merge_commit_sha?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    mergeable?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PullRequest
     */
    merged?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    merged_at?: any;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    merged_by?: any;
    /**
     * 
     * @type {Milestone}
     * @memberof PullRequest
     */
    milestone?: any;
    /**
     * 
     * @type {number}
     * @memberof PullRequest
     */
    number?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    patch_url?: any;
    /**
     * 
     * @type {StateType}
     * @memberof PullRequest
     */
    state?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    title?: any;
    /**
     * 
     * @type {Date}
     * @memberof PullRequest
     */
    updated_at?: any;
    /**
     * 
     * @type {string}
     * @memberof PullRequest
     */
    url?: any;
    /**
     * 
     * @type {User}
     * @memberof PullRequest
     */
    user?: any;
}
