/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Release represents a repository release
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {Array&lt;Attachment&gt;}
     * @memberof Release
     */
    assets?: any;
    /**
     * 
     * @type {User}
     * @memberof Release
     */
    author?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    created_at?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    draft?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    html_url?: any;
    /**
     * 
     * @type {number}
     * @memberof Release
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    prerelease?: any;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    published_at?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tag_name?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tarball_url?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    target_commitish?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    zipball_url?: any;
}
