/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Release represents a repository release
 * @export
 * @interface Release
 */
export interface Release {
    /**
     * 
     * @type {Array&lt;Attachment&gt;}
     * @memberof Release
     */
    assets?: any;
    /**
     * 
     * @type {User}
     * @memberof Release
     */
    author?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    body?: any;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    createdAt?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    draft?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Release
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Release
     */
    prerelease?: any;
    /**
     * 
     * @type {Date}
     * @memberof Release
     */
    publishedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tagName?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    tarballUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    targetCommitish?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    url?: any;
    /**
     * 
     * @type {string}
     * @memberof Release
     */
    zipballUrl?: any;
}
