/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Repository represents a repository
 * @export
 * @interface Repository
 */
export interface Repository {
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allow_merge_commits?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allow_rebase?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allow_rebase_explicit?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allow_squash_merge?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    archived?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    avatar_url?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    clone_url?: any;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    created_at?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    default_branch?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    default_merge_style?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    empty?: any;
    /**
     * 
     * @type {ExternalTracker}
     * @memberof Repository
     */
    external_tracker?: any;
    /**
     * 
     * @type {ExternalWiki}
     * @memberof Repository
     */
    external_wiki?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    fork?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    forks_count?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    full_name?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    has_issues?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    has_projects?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    has_pull_requests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    has_wiki?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    html_url?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    ignore_whitespace_conflicts?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    internal?: any;
    /**
     * 
     * @type {InternalTracker}
     * @memberof Repository
     */
    internal_tracker?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    mirror?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    mirror_interval?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    open_issues_count?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    open_pr_counter?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    original_url?: any;
    /**
     * 
     * @type {User}
     * @memberof Repository
     */
    owner?: any;
    /**
     * 
     * @type {Repository}
     * @memberof Repository
     */
    parent?: any;
    /**
     * 
     * @type {Permission}
     * @memberof Repository
     */
    permissions?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    _private?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    release_counter?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    ssh_url?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    stars_count?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    template?: any;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    updated_at?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    watchers_count?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    website?: any;
}
