/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Repository represents a repository
 * @export
 * @interface Repository
 */
export interface Repository {
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowMergeCommits?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowRebase?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowRebaseExplicit?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    allowSquashMerge?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    archived?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    avatarUrl?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    cloneUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    createdAt?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    defaultBranch?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    empty?: any;
    /**
     * 
     * @type {ExternalTracker}
     * @memberof Repository
     */
    externalTracker?: any;
    /**
     * 
     * @type {ExternalWiki}
     * @memberof Repository
     */
    externalWiki?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    fork?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    forksCount?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    fullName?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasIssues?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasProjects?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasPullRequests?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    hasWiki?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    htmlUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    ignoreWhitespaceConflicts?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    internal?: any;
    /**
     * 
     * @type {InternalTracker}
     * @memberof Repository
     */
    internalTracker?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    mirror?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    mirrorInterval?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    name?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    openIssuesCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    openPrCounter?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    originalUrl?: any;
    /**
     * 
     * @type {User}
     * @memberof Repository
     */
    owner?: any;
    /**
     * 
     * @type {Repository}
     * @memberof Repository
     */
    parent?: any;
    /**
     * 
     * @type {Permission}
     * @memberof Repository
     */
    permissions?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    _private?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    releaseCounter?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    size?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    sshUrl?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    starsCount?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Repository
     */
    template?: any;
    /**
     * 
     * @type {Date}
     * @memberof Repository
     */
    updatedAt?: any;
    /**
     * 
     * @type {number}
     * @memberof Repository
     */
    watchersCount?: any;
    /**
     * 
     * @type {string}
     * @memberof Repository
     */
    website?: any;
}
