/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * RepoTopicOptions a collection of repo topic names
 * @export
 * @interface RepoTopicOptions
 */
export interface RepoTopicOptions {
    /**
     * list of topic names
     * @type {Array&lt;string&gt;}
     * @memberof RepoTopicOptions
     */
    topics?: any;
}
