/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * RepositoryMeta basic repository information
 * @export
 * @interface RepositoryMeta
 */
export interface RepositoryMeta {
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    full_name?: any;
    /**
     * 
     * @type {number}
     * @memberof RepositoryMeta
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof RepositoryMeta
     */
    owner?: any;
}
