/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * StopWatch represent a running stopwatch
 * @export
 * @interface StopWatch
 */
export interface StopWatch {
    /**
     * 
     * @type {Date}
     * @memberof StopWatch
     */
    created?: any;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    duration?: any;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    issue_index?: any;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    issue_title?: any;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    repo_name?: any;
    /**
     * 
     * @type {string}
     * @memberof StopWatch
     */
    repo_owner_name?: any;
    /**
     * 
     * @type {number}
     * @memberof StopWatch
     */
    seconds?: any;
}
