/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * SubmitPullReviewOptions are options to submit a pending pull review
 * @export
 * @interface SubmitPullReviewOptions
 */
export interface SubmitPullReviewOptions {
    /**
     * 
     * @type {string}
     * @memberof SubmitPullReviewOptions
     */
    body?: any;
    /**
     * 
     * @type {ReviewStateType}
     * @memberof SubmitPullReviewOptions
     */
    event?: any;
}
