/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Team represents a team in an organization
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    can_create_org_repo?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    description?: any;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    includes_all_repositories?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    name?: any;
    /**
     * 
     * @type {Organization}
     * @memberof Team
     */
    organization?: any;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    permission?: TeamPermissionEnum;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof Team
     */
    units?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum TeamPermissionEnum {
    None = 'none',
    Read = 'read',
    Write = 'write',
    Admin = 'admin',
    Owner = 'owner'
}

