/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.15.0+dev-49-gaee5ef005
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * TopicResponse for returning topics
 * @export
 * @interface TopicResponse
 */
export interface TopicResponse {
    /**
     * 
     * @type {Date}
     * @memberof TopicResponse
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof TopicResponse
     */
    repo_count?: any;
    /**
     * 
     * @type {string}
     * @memberof TopicResponse
     */
    topic_name?: any;
    /**
     * 
     * @type {Date}
     * @memberof TopicResponse
     */
    updated?: any;
}
