/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * TrackedTime worked time for an issue / pr
 * @export
 * @interface TrackedTime
 */
export interface TrackedTime {
    /**
     * 
     * @type {Date}
     * @memberof TrackedTime
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof TrackedTime
     */
    id?: any;
    /**
     * 
     * @type {Issue}
     * @memberof TrackedTime
     */
    issue?: any;
    /**
     * deprecated (only for backwards compatibility)
     * @type {number}
     * @memberof TrackedTime
     */
    issueId?: any;
    /**
     * Time in seconds
     * @type {number}
     * @memberof TrackedTime
     */
    time?: any;
    /**
     * deprecated (only for backwards compatibility)
     * @type {number}
     * @memberof TrackedTime
     */
    userId?: any;
    /**
     * 
     * @type {string}
     * @memberof TrackedTime
     */
    userName?: any;
}
