/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * TransferRepoOption options when transfer a repository's ownership
 * @export
 * @interface TransferRepoOption
 */
export interface TransferRepoOption {
    /**
     * 
     * @type {string}
     * @memberof TransferRepoOption
     */
    newOwner: any;
    /**
     * ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.
     * @type {Array&lt;number&gt;}
     * @memberof TransferRepoOption
     */
    teamIds?: any;
}
