/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * User represents a user
 * @export
 * @interface User
 */
export interface User {
    /**
     * URL to the user's avatar
     * @type {string}
     * @memberof User
     */
    avatarUrl?: any;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    created?: any;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: any;
    /**
     * the user's full name
     * @type {string}
     * @memberof User
     */
    fullName?: any;
    /**
     * the user's id
     * @type {number}
     * @memberof User
     */
    id?: any;
    /**
     * Is the user an administrator
     * @type {boolean}
     * @memberof User
     */
    isAdmin?: any;
    /**
     * User locale
     * @type {string}
     * @memberof User
     */
    language?: any;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastLogin?: any;
    /**
     * the user's username
     * @type {string}
     * @memberof User
     */
    login?: any;
}
