/* tslint:disable */
/* eslint-disable */
/**
 * Gitea API.
 * This documentation describes the Gitea API.
 *
 * OpenAPI spec version: 1.14.0&#43;dev-693-g487f2ee41
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * WatchInfo represents an API watch status of one repository
 * @export
 * @interface WatchInfo
 */
export interface WatchInfo {
    /**
     * 
     * @type {Date}
     * @memberof WatchInfo
     */
    createdAt?: any;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    ignored?: any;
    /**
     * 
     * @type {any}
     * @memberof WatchInfo
     */
    reason?: any;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    repositoryUrl?: any;
    /**
     * 
     * @type {boolean}
     * @memberof WatchInfo
     */
    subscribed?: any;
    /**
     * 
     * @type {string}
     * @memberof WatchInfo
     */
    url?: any;
}
